### ISSUE TITLE
Upgrading to 3.3.4 mysql notes should mention `verifyServerCertificate=false` setting

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#687]
**Describe the bug**

- [ ] Document config difference between Mysql driver and MariaDB driver. `trustServerCertificate=true` should be used instead of `verifyServerCertificate=false`
- [ ] Document method of downloading and installing Mysql connector/J driver directly if desired.

From JP:

> looks like mariadb driver is not working as expected when the db is TLS configured 
original jdbc working fine using com.mysql.cj.jdbc.Driver driver:

```
dataSource.url = jdbc:mysql://host:3307/db?autoReconnect=true&useSSL=true&verifyServerCertificate=false&requireSSL=true
```

> using mariadb driver org.mariadb.jdbc.Driver  same url:
> rundeck won't start showing this output:

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450) ~[?:1.8.0_265]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317) ~[?:1.8.0_265]
	at sun.security.validator.Validator.validate(Validator.java:262) ~[?:1.8.0_265]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330) ~[?:1.8.0_265]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237) ~[?:1.8.0_265]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[?:1.8.0_265]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1670) ~[?:1.8.0_265]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:226) ~[?:1.8.0_265]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1082) ~[?:1.8.0_265]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:1010) ~[?:1.8.0_265]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1079) ~[?:1.8.0_265]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1388) ~[?:1.8.0_265]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1416) ~[?:1.8.0_265]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1400) ~[?:1.8.0_265]
```

> looks like `verifyServerCertificate=false` is not a mariadb attribute: [info here](https://mariadb.com/kb/en/about-mariadb-connector-j/#tls-parameters)
> i changed above attribute for `trustServerCertificate=true` and the connection works fine now.

**Source page**

https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.3.4.html#mysql

**Comment by gschueler** [comment]
Note: can link to the mysql connector/J download instructions here https://docs.rundeck.com/docs/administration/configuration/database/mysql.html#mysql-jdbc-driver

**Comment by fdevans** [comment]
Thanks for the report. As part of a cleanup of our documentation issue tracker, we're closing issues older than 12 months — the docs site has been substantially reorganized and rewritten since older reports were filed, so we can't be confident this still applies to the current content. This isn't a judgment that the report was invalid.

If this is still an issue on the current docs site (docs.rundeck.com), please open a new issue linking the specific page and describing what's wrong. Please don't reopen this issue — a fresh issue keeps things properly tracked against the current site.

Thanks for your patience,
The Rundeck Team
